language: objective-c
osx_image: xcode8.2
sudo: false

before_install:
  - gem install fastlane

# install:
#   - pod install

# after_install:

before_script:
  - fastlane snapshot reset_simulators --force
      
script:
  - xcodebuild clean build test -project FastCampusRickyManualLayoutTest.xcodeproj -scheme FastCampusRickyManualLayoutTest -destination "platform=iOS Simulator,name=iPhone 7,OS=10.2"




